import React from 'react';
export const mapsDetails = () => <div>maps distinct</div>;
export const maps_detail_0 = (p:any)=> <div>maps 0 world maps</div>;
export const maps_detail_1 = (p:any)=> <div>maps 1 regions</div>;
export const maps_detail_2 = (p:any)=> <div>maps 2 POIs</div>;
export const maps_detail_3 = (p:any)=> <div>maps 3 coordinates</div>;
export const maps_detail_4 = (p:any)=> <div>maps 4 world maps</div>;
export const maps_detail_5 = (p:any)=> <div>maps 5 regions</div>;
export const maps_detail_6 = (p:any)=> <div>maps 6 POIs</div>;
export const maps_detail_7 = (p:any)=> <div>maps 7 coordinates</div>;
export const maps_detail_8 = (p:any)=> <div>maps 8 world maps</div>;
export const maps_detail_9 = (p:any)=> <div>maps 9 regions</div>;
export const maps_detail_10 = (p:any)=> <div>maps 10 POIs</div>;
export const maps_detail_11 = (p:any)=> <div>maps 11 coordinates</div>;
export const maps_detail_12 = (p:any)=> <div>maps 12 world maps</div>;
export const maps_detail_13 = (p:any)=> <div>maps 13 regions</div>;
export const maps_detail_14 = (p:any)=> <div>maps 14 POIs</div>;
export const maps_detail_15 = (p:any)=> <div>maps 15 coordinates</div>;
export const maps_detail_16 = (p:any)=> <div>maps 16 world maps</div>;
export const maps_detail_17 = (p:any)=> <div>maps 17 regions</div>;
export const maps_detail_18 = (p:any)=> <div>maps 18 POIs</div>;
export const maps_detail_19 = (p:any)=> <div>maps 19 coordinates</div>;