import React from 'react';
export const consistencyDetails = () => <div>consistency distinct</div>;
export const consistency_detail_0 = (p:any)=> <div>consistency 0 born 1990 war 1985</div>;
export const consistency_detail_1 = (p:any)=> <div>consistency 1 timeline</div>;
export const consistency_detail_2 = (p:any)=> <div>consistency 2 contradictions</div>;
export const consistency_detail_3 = (p:any)=> <div>consistency 3 flags</div>;
export const consistency_detail_4 = (p:any)=> <div>consistency 4 born 1990 war 1985</div>;
export const consistency_detail_5 = (p:any)=> <div>consistency 5 timeline</div>;
export const consistency_detail_6 = (p:any)=> <div>consistency 6 contradictions</div>;
export const consistency_detail_7 = (p:any)=> <div>consistency 7 flags</div>;
export const consistency_detail_8 = (p:any)=> <div>consistency 8 born 1990 war 1985</div>;
export const consistency_detail_9 = (p:any)=> <div>consistency 9 timeline</div>;
export const consistency_detail_10 = (p:any)=> <div>consistency 10 contradictions</div>;
export const consistency_detail_11 = (p:any)=> <div>consistency 11 flags</div>;
export const consistency_detail_12 = (p:any)=> <div>consistency 12 born 1990 war 1985</div>;
export const consistency_detail_13 = (p:any)=> <div>consistency 13 timeline</div>;
export const consistency_detail_14 = (p:any)=> <div>consistency 14 contradictions</div>;
export const consistency_detail_15 = (p:any)=> <div>consistency 15 flags</div>;
export const consistency_detail_16 = (p:any)=> <div>consistency 16 born 1990 war 1985</div>;
export const consistency_detail_17 = (p:any)=> <div>consistency 17 timeline</div>;
export const consistency_detail_18 = (p:any)=> <div>consistency 18 contradictions</div>;
export const consistency_detail_19 = (p:any)=> <div>consistency 19 flags</div>;