import React from 'react';
export const frontendDetails = () => <div>frontend distinct</div>;
export const frontend_detail_0 = (p:any)=> <div>frontend 0 tree</div>;
export const frontend_detail_1 = (p:any)=> <div>frontend 1 graph</div>;
export const frontend_detail_2 = (p:any)=> <div>frontend 2 timeline viz</div>;
export const frontend_detail_3 = (p:any)=> <div>frontend 3 tree</div>;
export const frontend_detail_4 = (p:any)=> <div>frontend 4 graph</div>;
export const frontend_detail_5 = (p:any)=> <div>frontend 5 timeline viz</div>;
export const frontend_detail_6 = (p:any)=> <div>frontend 6 tree</div>;
export const frontend_detail_7 = (p:any)=> <div>frontend 7 graph</div>;
export const frontend_detail_8 = (p:any)=> <div>frontend 8 timeline viz</div>;
export const frontend_detail_9 = (p:any)=> <div>frontend 9 tree</div>;
export const frontend_detail_10 = (p:any)=> <div>frontend 10 graph</div>;
export const frontend_detail_11 = (p:any)=> <div>frontend 11 timeline viz</div>;
export const frontend_detail_12 = (p:any)=> <div>frontend 12 tree</div>;
export const frontend_detail_13 = (p:any)=> <div>frontend 13 graph</div>;
export const frontend_detail_14 = (p:any)=> <div>frontend 14 timeline viz</div>;
export const frontend_detail_15 = (p:any)=> <div>frontend 15 tree</div>;
export const frontend_detail_16 = (p:any)=> <div>frontend 16 graph</div>;
export const frontend_detail_17 = (p:any)=> <div>frontend 17 timeline viz</div>;
export const frontend_detail_18 = (p:any)=> <div>frontend 18 tree</div>;
export const frontend_detail_19 = (p:any)=> <div>frontend 19 graph</div>;